In [5]:
import torch
import numpy as np

In [9]:
# 1.基本张量创建
# 1.1 传入标量
tensor1 = torch.tensor(5)
print(tensor1)

# 1.2 传入列表
tensor2 = torch.tensor([[1,2,3], [4,5,6]])
print(tensor2)

# 1.3 传入ndarray
tensor3 = torch.tensor(np.array([[1,2,3], [4,5,6]]))
print(tensor3)

# 1.4 创建指定形状的张量
# 使用大写Tensor,默认使用浮点数
tensor4 = torch.Tensor(3, 2, 3)
print(tensor4)

# 1.5 创建制定类型Tensor
# FloatTensor, DoubleTensor, BoolTensor
tensor5 = torch.IntTensor(3, 2, 3)
print(tensor5)
tensor6 = torch.tensor([1,2,3], dtype=torch.int)
print(tensor6)

tensor(5)
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[[2.0531e-25, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
tensor([[[375839641,         0,         0],
         [        0,         0,         0]],

        [[        0,         0,         0],
         [        0,         0,         0]],

        [[        0,         0,         0],
         [        0,         0,         0]]], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [12]:
# 2.指定区间
tensor7 = torch.arange(1, 10, 1)
print(tensor7)

# 5是数量
tensor8 = torch.linspace(1, 10, 5)
print(tensor8)

# 在指数区间内创建张量
tensor9 = torch.logspace(1, 10, 5, base=2)
print(tensor9)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([   2.0000,    9.5137,   45.2548,  215.2695, 1024.0000])


In [ ]:
# 3.按照数值填充
torch.zeros()
torch.zeros_like()
torch.ones()
torch.ones_like()
torch.full()
torch.full_like()
torch.empty()
torch.empty_like()

# 单位矩阵
torch.eye()

In [ ]:
# 4.随机张量生成
torch.rand() #[0,1)上均匀分布
torch.rand_like()
torch.randn(3, 2) # 标准正态分布
torch.randn_like(tensor1)
torch.normal() # 自定义正态分布
torch.randint(0, 100, (2,3)) # [low, high)
torch.randint_like(tensor5, 1, 10)

In [ ]:
# 生成随即排列的序列
torch.randperm(10)

# 查看随机种子
torch.random.initial_seed()
# 设置随机种子
torch.manual_seed(52)