In [1]:
import numpy as np
import torch

In [ ]:
# 张量元素类型转换
tensor0 = torch.tensor([1,2,3])
print(tensor0.dtype)
tensor1 = tensor0.type(torch.float64)
print(tensor1.dtype)

In [ ]:
# 直接转换
tensor2 = tensor0.int() # bool(), float(), double()

In [4]:
# tensor --> ndarray
tensor2 = torch.rand(3, 2)
np_array1 = tensor2.numpy()
print(np_array1)

# tensor与numpy共享内存
tensor2[:, 0] = 10
print(tensor2)
print(np_array1)

# 使用copy方法避免共享内存
np_array2 = tensor2.numpy().copy()
tensor2[:, 0] = 100
print(tensor2)
print(np_array2)


[[0.9494778  0.9115053 ]
 [0.6819488  0.99960816]
 [0.7559363  0.17714208]]
tensor([[10.0000,  0.9115],
        [10.0000,  0.9996],
        [10.0000,  0.1771]])
[[10.          0.9115053 ]
 [10.          0.99960816]
 [10.          0.17714208]]
tensor([[100.0000,   0.9115],
        [100.0000,   0.9996],
        [100.0000,   0.1771]])
[[10.          0.9115053 ]
 [10.          0.99960816]
 [10.          0.17714208]]


In [6]:
# ndarray --> tensor,仍是共享内存
np_array = np.random.randn(3,2)
tensor3 = torch.from_numpy(np_array)
print(np_array)
print(tensor3)

[[-0.23086823  0.18705154]
 [-1.18116748  1.888383  ]
 [-0.179991   -1.43655116]]
tensor([[-0.2309,  0.1871],
        [-1.1812,  1.8884],
        [-0.1800, -1.4366]], dtype=torch.float64)


In [8]:
# 使用tensor方法，将ndarray转换为tensor,不共享内存了
np_array = np.random.randn(3)
tensor4 = torch.tensor(np_array)
np_array[0] = 100
print(np_array)
print(tensor4)

[100.          -1.54162573   1.21076765]
tensor([-0.7277, -1.5416,  1.2108], dtype=torch.float64)
