In [2]:
import numpy as np
import torch

In [3]:
# + - * / 非原地操作
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1 + 10)
print(tensor1)

tensor([[16, 19, 14],
        [18, 14, 18]])
tensor([[6, 9, 4],
        [8, 4, 8]])


In [4]:
# 原地操作, add_, pow_, sqrt_, exp_, log_
print(tensor1.add_(10))
print(tensor1)

tensor([[16, 19, 14],
        [18, 14, 18]])
tensor([[16, 19, 14],
        [18, 14, 18]])


In [5]:
# 非原地操作 add, pow, sqrt, exp, log
print(tensor1.add(10))
print(tensor1)

tensor([[26, 29, 24],
        [28, 24, 28]])
tensor([[16, 19, 14],
        [18, 14, 18]])


In [6]:
# 矩阵相关运算
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1 + tensor2)
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

# 点乘
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

# 张量的矩阵乘法
# 张量中最后面两个维度要可以直接进行矩阵乘法
tensor3 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 2*2*3
tensor4 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]]) # 2*3*2
print(tensor3 @tensor4)

# dot方法必须是一维向量相乘
tensor5 = torch.tensor([1,2,3])
tensor6 = torch.tensor([4,5,6])
print(tensor5.dot(tensor6))

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[[22, 28],
         [49, 64]],

        [[22, 28],
         [49, 64]]])
tensor(32)


In [8]:
# 节省内存
X = torch.randint(low=1, high=10, size=(3, 2, 4))
Y = torch.randint(low=1, high=10, size=(3, 2, 4))
print(id(X))
# 创建了新的对象，所以id不一样
X = X * Y
print(id(X))
# 使用相同的对象来存储，id一样
X *= Y
print(id(X))

137370238297152
137370547510144
137370547510144


In [13]:
X = torch.randint(low=1, high=10, size=(3, 2, 4))
Y = torch.randint(low=1, high=10, size=(3, 4, 1))
print(id(X))
# 这里会报错，因为X与Y相乘以后的shape与X原始的shape不一样，torch不支持，但是numpy支持
# X @= Y
print(X.shape)
print((X @ Y).shape)

X2 = torch.randint(low=1, high=10, size=(3, 2, 4))
Z = torch.randint(low=1, high=10, size=(3, 4, 4))
# id也不同，因为矩阵乘法底层就不支持直接写回
print(id(X2))
X2 @= Z
print(id(X2))

137368613489152
torch.Size([3, 2, 4])
torch.Size([3, 2, 1])
137368613488272
137368613488352
