In [1]:
import numpy as np
import torch

In [2]:
# + - * / 非原地操作
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1 + 10)
print(tensor1)

tensor([[16, 16, 13],
        [12, 12, 14]])
tensor([[6, 6, 3],
        [2, 2, 4]])


In [3]:
# 原地操作, add_, pow_, sqrt_, exp_, log_
print(tensor1.add_(10))
print(tensor1)

tensor([[16, 16, 13],
        [12, 12, 14]])
tensor([[16, 16, 13],
        [12, 12, 14]])


In [4]:
# 非原地操作 add, pow, sqrt, exp, log
print(tensor1.add(10))
print(tensor1)

tensor([[26, 26, 23],
        [22, 22, 24]])
tensor([[16, 16, 13],
        [12, 12, 14]])


In [13]:
# 矩阵相关运算
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor2 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor1 + tensor2)
print(tensor1 * tensor2)
print(tensor1.mul(tensor2))

# 点乘
print(tensor1 @ tensor2)
print(tensor1.matmul(tensor2))

# 张量的矩阵乘法
# 张量中最后面两个维度要可以直接进行矩阵乘法
tensor3 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 2*2*3
tensor4 = torch.tensor([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]]) # 2*3*2
print(tensor3 @tensor4)

# dot方法必须是一维向量相乘
tensor5 = torch.tensor([1,2,3])
tensor6 = torch.tensor([4,5,6])
print(tensor5.dot(tensor6))

tensor([[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])
tensor([[[22, 28],
         [49, 64]],

        [[22, 28],
         [49, 64]]])
tensor(32)
