In [1]:
import torch

In [2]:
tensor1 = torch.randint(low=0, high=10, size=(3,2,4))

print(tensor1)
print(tensor1[0, 1, 2])

tensor([[[6, 3, 4, 7],
         [6, 3, 6, 2]],

        [[7, 7, 2, 8],
         [5, 8, 8, 9]],

        [[0, 6, 7, 9],
         [9, 1, 6, 3]]])
tensor(6)


In [3]:
# 所有矩阵第二行
print(tensor1[:, 1])

tensor([[6, 3, 6, 2],
        [5, 8, 8, 9],
        [9, 1, 6, 3]])


In [7]:
# 范围索引
print(tensor1[1:])
print(tensor1[1:, 0:, 2:3])

# 支持步长
print(tensor1[1:, 0:, 2:3:1])

tensor([[[7, 7, 2, 8],
         [5, 8, 8, 9]],

        [[0, 6, 7, 9],
         [9, 1, 6, 3]]])
tensor([[[2],
         [8]],

        [[7],
         [6]]])
tensor([[[2],
         [8]],

        [[7],
         [6]]])


In [9]:
# 列表索引
# 对应匹配，相当于0矩阵第0行，1矩阵第1行
print(tensor1[[0, 1], [0, 1]])

# 0矩阵的前两行，1矩阵的前两行
print(tensor1[[[0], [1]], [0, 1]])


tensor([[6, 3, 4, 7],
        [5, 8, 8, 9]])
tensor([[[6, 3, 4, 7],
         [6, 3, 6, 2]],

        [[7, 7, 2, 8],
         [5, 8, 8, 9]]])


In [19]:
# 布尔索引
mask = tensor1 > 5
print(mask)
print(tensor1[mask])

# 选取首元素大于5的所有行
mask2 = tensor1[:, :, 0] > 5
print(mask2)
print(tensor1[mask2])

tensor([[[ True, False, False,  True],
         [ True, False,  True, False]],

        [[ True,  True, False,  True],
         [False,  True,  True,  True]],

        [[False,  True,  True,  True],
         [ True, False,  True, False]]])
tensor([6, 7, 6, 6, 7, 7, 8, 8, 8, 9, 6, 7, 9, 9, 6])
tensor([[ True,  True],
        [ True, False],
        [False,  True]])
tensor([[6, 3, 4, 7],
        [6, 3, 6, 2],
        [7, 7, 2, 8],
        [9, 1, 6, 3]])


In [18]:
# 选取第二个元素大于5的所有列
mask = tensor1[:, 1, :] > 5
print(mask)
#会报错,shape mismatch
#print(tensor1[mask])

#转换维度
# 0维不变，1维和2维互换
tensor2 = tensor1.permute(0, 2, 1)
print(tensor2)
print(tensor2[mask].T)

tensor([[ True, False,  True, False],
        [False,  True,  True,  True],
        [ True, False,  True, False]])
tensor([[[6, 6],
         [3, 3],
         [4, 6],
         [7, 2]],

        [[7, 5],
         [7, 8],
         [2, 8],
         [8, 9]],

        [[0, 9],
         [6, 1],
         [7, 6],
         [9, 3]]])
tensor([[6, 4, 7, 2, 8, 0, 7],
        [6, 6, 8, 8, 9, 9, 6]])
