In [17]:
import torch

In [18]:
# 交换维度
tensor1 = torch.randint(low=0, high=10, size=(3, 2, 4))
print(tensor1)

# 只能交换两个维度
print(tensor1.transpose(1, 2))

tensor([[[1, 7, 5, 7],
         [1, 2, 8, 4]],

        [[1, 2, 8, 5],
         [6, 6, 7, 0]],

        [[7, 0, 8, 3],
         [4, 3, 0, 1]]])
tensor([[[1, 1],
         [7, 2],
         [5, 8],
         [7, 4]],

        [[1, 6],
         [2, 6],
         [8, 7],
         [5, 0]],

        [[7, 4],
         [0, 3],
         [8, 0],
         [3, 1]]])


In [19]:
# 调整维度, 代表的是第几维
print(tensor1.permute(0, 2, 1))

tensor([[[1, 1],
         [7, 2],
         [5, 8],
         [7, 4]],

        [[1, 6],
         [2, 6],
         [8, 7],
         [5, 0]],

        [[7, 4],
         [0, 3],
         [8, 0],
         [3, 1]]])


In [20]:
# 调整形状
print(tensor1.reshape((2, 12)))
# view调整形状，需要内存连续
print(tensor1.is_contiguous())
print(tensor1.view(-1, 2))

tensor([[1, 7, 5, 7, 1, 2, 8, 4, 1, 2, 8, 5],
        [6, 6, 7, 0, 7, 0, 8, 3, 4, 3, 0, 1]])
True
tensor([[1, 7],
        [5, 7],
        [1, 2],
        [8, 4],
        [1, 2],
        [8, 5],
        [6, 6],
        [7, 0],
        [7, 0],
        [8, 3],
        [4, 3],
        [0, 1]])


In [21]:
# 增减/删除维度
# 增加
tensor2 = torch.tensor([1, 2, 3])
print(tensor2)
print("-----")
# 在第一个维度增加
print(tensor2.unsqueeze(dim=0))
print(tensor2.unsqueeze(dim=0).shape)
print("-----")
# 在第二个维度增加
print(tensor2.unsqueeze(dim=1))
print(tensor2.unsqueeze(dim=1).shape)
# 在最后一个维度增加
print(tensor2.unsqueeze(dim=-1).shape)

tensor([1, 2, 3])
-----
tensor([[1, 2, 3]])
torch.Size([1, 3])
-----
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
torch.Size([3, 1])


In [22]:
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(tensor3.shape)
print("------")
print(tensor3.unsqueeze(dim=1))
print(tensor3.unsqueeze(dim=1).shape)

torch.Size([3, 3])
------
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
torch.Size([3, 1, 3])


In [23]:
# 删除,只能删除大小为1的维度
print(tensor3.unsqueeze_(dim=1))
print(tensor3.shape)
print("-----")
print(tensor3.squeeze_(dim=1))
print(tensor3.shape)

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
torch.Size([3, 1, 3])
-----
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [24]:
# 拼接, 除拼接维度以外，其他维度必须相同
tensor4 = torch.randint(low=0, high=10, size=(3, 2, 4))
tensor5 = torch.randint(low=0, high=10, size=(3, 1, 4))
print(torch.cat([tensor4, tensor5], dim=1))

tensor([[[0, 6, 6, 1],
         [0, 5, 4, 9],
         [4, 6, 6, 1]],

        [[8, 1, 1, 3],
         [5, 2, 7, 0],
         [7, 1, 5, 6]],

        [[3, 9, 5, 4],
         [8, 5, 6, 0],
         [1, 1, 8, 0]]])


In [28]:
# 堆叠, shape必须完全一样才能堆叠
tensor6 = torch.randint(low=0, high=10, size=(3, 2, 4))
tensor7 = torch.stack([tensor4, tensor6])
print(tensor7)
print(tensor7.shape)

tensor([[[[0, 6, 6, 1],
          [0, 5, 4, 9]],

         [[8, 1, 1, 3],
          [5, 2, 7, 0]],

         [[3, 9, 5, 4],
          [8, 5, 6, 0]]],


        [[[4, 2, 7, 8],
          [4, 4, 4, 9]],

         [[0, 2, 6, 5],
          [1, 7, 3, 3]],

         [[6, 1, 7, 6],
          [0, 9, 9, 3]]]])
torch.Size([2, 3, 2, 4])
