In [15]:
import torch

In [16]:
# 定义输入数据x和y
x = torch.tensor(10.0)
y = torch.tensor([[3.0]])
w = torch.rand(1,1,requires_grad=True)
b = torch.rand(1,1,requires_grad=True)

z = w * x + b
print(z)
print(z.requires_grad)

tensor([[2.4338]], grad_fn=<AddBackward0>)
True


In [17]:
# loss function
loss = torch.nn.MSELoss()
loss_value= loss(z, y)
print(loss_value)
loss_value.backward()
print(w.grad)
print(b.grad)

# 只有是叶子节点，计算grad才有意义
print(x.is_leaf)
print(y.is_leaf)
print(w.is_leaf)
print(b.is_leaf)
print(z.is_leaf)

tensor(0.3206, grad_fn=<MseLossBackward0>)
tensor([[-11.3234]])
tensor([[-1.1323]])
True
True
True
True
False
