In [1]:
import torch

In [2]:
# x与y底层数据共享
x = torch.tensor([1.0, 2, 3], requires_grad=True)
y = x.detach()
print(x)
print(y)

tensor([1., 2., 3.], requires_grad=True)
tensor([1., 2., 3.])


In [3]:
z1 = x ** 2
z2 = y ** 2

print(z1)
print(z2)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([1., 4., 9.])
