In [3]:
import numpy as np

In [5]:
arr = np.array([[1,2,3], [4,6,6]])
print(arr)

[[1 2 3]
 [4 6 6]]


array([[1, 2, 3],
       [4, 6, 6]])

In [ ]:
# 图形化展示矩阵
arr

In [7]:
print(arr.shape) # 矩阵形状
print(arr.size) # 矩阵元素数量
print(arr.dtype) # 矩阵匀速类型
print(arr.ndim) # 矩阵维度
print(arr.itemsize) # 矩阵元素字节数

(2, 3)
6
int64
2
