In [1]:
import numpy as np

In [ ]:
# array, 会将原来的数据重新拷贝一份
# asarray, 不会将原来的数据重新拷贝一份，会共用同一内存

In [3]:
# 通过列表创建矩阵
data = [1,2,3,4,5,6,7,8,9,10]
arr = np.array(data)
print(arr)
print(arr.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [4]:
arr2 = np.array(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
arr3 = np.asarray(arr)
print(id(arr))
print(id(arr3))

132894073779856
132894073779856


In [6]:
# zeros,用0填充
# ones,用1填充
# empty,返回类型和形状未初始化的矩阵
# 上述三个方法填充的都是float64

arr4 = np.zeros((2,3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# zeros_like
# ones_like
# empty_like
# 返回与给定数组具有相同形状的填充数组
arr5 = np.ones_like(arr4)
print(arr5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# full: 返回给定形状和类型的新数组，用指定的值填充
# full_like: 返回与给定数组具有相同形状和类型的新数组，用指定的值填充
arr6 = np.full((2,3),5)
print(arr6)

arr7 = np.full_like(arr6,8)
print(arr7)


[[5 5 5]
 [5 5 5]]
[[8 8 8]
 [8 8 8]]


In [10]:
# arange： 返回在一定范围内用均匀间隔的值填充的一维数组
arr8 = np.arange(0, 10, 2)
print(arr8)

[0 2 4 6 8]


In [15]:
# random.rand():返回给定形状的数组，用[0,1)上均匀分布来填充样本
# random.randint():返回给定形状的数组，用从低位到高位上均匀分布的随机整数来填充
# random.uniform():返回给定形状的数组，用从低位到高位上均匀分布的随机浮点数来填充
# random.randn():返回给定形状的数组，用标准正态分布的随机样本来填充
arr9 = np.random.rand(2,3)
print(arr9)
arr10 = np.random.randint(0,2,(2,3))
print(arr10)
arr11 = np.random.uniform(100,200,(2,3))
print(arr11)
arr12 = np.random.randn(2,3)
print(arr12)

[[0.29175387 0.66347156 0.97514767]
 [0.16075127 0.91882125 0.79029387]]
[[0 1 1]
 [0 0 0]]
[[103.37978913 127.78174302 161.02289169]
 [132.11459332 104.15169299 115.06811038]]
[[-0.48054598  2.29203386 -0.21836804]
 [-2.82570588 -1.6175284  -0.4441773 ]]
