In [1]:
import numpy as np

In [ ]:
# np.abs:绝对值
# np.ceil:向上取整
# np.floor:向下取整
# np.rint:四舍五入
# np.isnan:判断是否为Nan
# np.multipy:元素相乘,如果第二个参数是数字，则所有的元素都乘这个数字，如果是个数组，则对应位置的元素相乘
# np.divide:元素相除,如果第二个参数是数字，则所有的元素都除这个数字，如果是个数组，则对应位置的元素相除
# np.where(condition, x, y): x if condition else y，三元运算符

In [5]:
# np.sum
# np.mean
# np.max
# np.min
# np.std: 标准差
# np.var: 方差
# np.argmax: 最大值索引
# np.argmin
# np.cumsum: 返回一个一维数组，每个元素都是都是前面的累加和
# np.cumprod: 返回一个一维数组，每个元素都是都是前面的累乘积

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.cumsum(arr))
print(np.cumsum(arr, axis=0))
print(np.cumprod(arr))
print(np.cumprod(arr, axis=1))

[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[     1      2      6     24    120    720   5040  40320 362880]
[[  1   2   6]
 [  4  20 120]
 [  7  56 504]]


In [6]:
# np.any: 有一个元素满足条件即返回true
# np.all: 所有元素满足条件才返回true
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.any(arr2 > 3))
print(np.all(arr2 < 3))

True
False


In [10]:
# np.sort:
arr3 = np.random.randint(0,10,(3,3))
print(arr3)
print(np.sort(arr3, axis=0))
print(np.sort(arr3, axis=1))

[[0 7 5]
 [3 4 8]
 [5 9 2]]
[[0 4 2]
 [3 7 5]
 [5 9 8]]
[[0 5 7]
 [3 4 8]
 [2 5 9]]


In [13]:
# 基本运算
# 任何两个数组拥有相同的形状，运算是在对应的元素上进行的
arr4 = np.random.randint(0,10,(3,3))
arr5 = np.random.randint(0,10,(3,3))
print(arr4)
print(arr5)
print(arr4 + arr5)
print(arr4 > arr5)
print(arr4 + 100)

[[4 2 8]
 [8 8 8]
 [8 7 5]]
[[7 7 0]
 [4 9 2]
 [5 3 2]]
[[11  9  8]
 [12 17 10]
 [13 10  7]]
[[False False  True]
 [ True False  True]
 [ True  True  True]]
[[104 102 108]
 [108 108 108]
 [108 107 105]]
