In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(0, 10, (3,2))
arr2 = np.random.randint(0, 10, (2,3))

# 矩阵乘法
print(np.dot(arr1, arr2))
print(arr1.dot(arr2))
print(arr1 @ arr2)

[[95 21 30]
 [ 8  0  4]
 [96 24 28]]
[[95 21 30]
 [ 8  0  4]
 [96 24 28]]
[[95 21 30]
 [ 8  0  4]
 [96 24 28]]
