In [12]:
import pandas as pd

In [13]:
mango_series = pd.Series([4,5,6,3,1])
apple_series = pd.Series([5,4,3,0,2])
banana_series = pd.Series([2,3,5,2,7])

# DataFrame是由多个Series组成的
# 可以用index指定行索引，用columns指定列的名字和顺序
df = pd.DataFrame({"mango": mango_series, "apple": apple_series, "banana": banana_series})
df

mango  apple  banana
0      4      5       2
1      5      4       3
2      6      3       5
3      3      0       2
4      1      2       7

In [14]:
# index
# columns
# value
# ndim
# shape
# size
# dtype
# name
# loc: 显示索引，切片
# iloc: 隐示索引，切片
# at: 访问单个元素
# iat
# T: 转置

print(df.index)
print(df.columns)
print(df.values)
print(df.ndim)
print(df.T)
print(df.at[1, "mango"])

RangeIndex(start=0, stop=5, step=1)
Index(['mango', 'apple', 'banana'], dtype='object')
[[4 5 2]
 [5 4 3]
 [6 3 5]
 [3 0 2]
 [1 2 7]]
2
        0  1  2  3  4
mango   4  5  6  3  1
apple   5  4  3  0  2
banana  2  3  5  2  7
5


In [15]:
print(df.loc[0:2, "mango":"apple"])
print("---------------")
print(df.loc[[0,3], "banana"])
print("---------------")
print(df.loc[:, "mango":"apple"])
print("---------------")

print(df.iloc[:, 2])

   mango  apple
0      4      5
1      5      4
2      6      3
---------------
0    2
3    2
Name: banana, dtype: int64
---------------
   mango  apple
0      4      5
1      5      4
2      6      3
3      3      0
4      1      2
---------------
0    2
1    3
2    5
3    2
4    7
Name: banana, dtype: int64


In [16]:
# head
# tail
# isin: 判断元素是否在Series
# isna: 判断是否为Nan
# np.sum
# np.mean
# np.max
# np.min
# np.std: 标准差
# np.var: 方差

print(df["banana"].sum())

19


In [17]:
# bool索引
print(df[df["banana"] > 2])

   mango  apple  banana
1      5      4       3
2      6      3       5
4      1      2       7


In [18]:
df["banana"] = df["banana"] * 2
print(df)

   mango  apple  banana
0      4      5       4
1      5      4       6
2      6      3      10
3      3      0       4
4      1      2      14


In [19]:
# 修改操作
# 增加新的列
df["kejun"] = [1,2,3,4,5]
print(df)

# 取多列数据
# ["banana"] 本质上是一个列表，包含了多个列名，返回的是一个DataFrame对象
print(df[["banana"]])
print(type(df["banana"])) # Series
print(type(df[["banana"]])) # DataFrame
print("---------------")

# 修改index名
df.index = ["a", "b", "c", "d", "e"]
print(df)

# 修改列名
df.columns = ["A", "B", "C", "D"]
print(df)

   mango  apple  banana  kejun
0      4      5       4      1
1      5      4       6      2
2      6      3      10      3
3      3      0       4      4
4      1      2      14      5
   banana
0       4
1       6
2      10
3       4
4      14
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
---------------
   mango  apple  banana  kejun
a      4      5       4      1
b      5      4       6      2
c      6      3      10      3
d      3      0       4      4
e      1      2      14      5
   A  B   C  D
a  4  5   4  1
b  5  4   6  2
c  6  3  10  3
d  3  0   4  4
e  1  2  14  5
