In [3]:
import torch
import torch.nn as nn

In [4]:
# linear layer
linear = nn.Linear(5,3)

In [5]:
# 常数初始化
print(linear.weight)
nn.init.zeros_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.1751,  0.0089, -0.4184, -0.2237, -0.3713],
        [-0.0922,  0.0012,  0.1360, -0.4149,  0.2434],
        [ 0.0689, -0.0332, -0.0960, -0.0875, -0.2531]], requires_grad=True)
Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [6]:
# linear.weight应该是5*3，但是pytorch默认使用转置来表示
nn.init.ones_(linear.weight)
print(linear.weight)
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([10., 10., 10.], requires_grad=True)


In [7]:
# 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]], requires_grad=True)


In [8]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, a=1, b=10)
print(linear.weight)

Parameter containing:
tensor([[2.8782, 6.9402, 1.6481, 9.3268, 2.0404],
        [6.8266, 3.0897, 5.4265, 6.6689, 2.3449],
        [4.8730, 5.5342, 7.5224, 5.9853, 4.8671]], requires_grad=True)


In [9]:
# 正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1)
print(linear.weight)

Parameter containing:
tensor([[ 1.7985,  0.7692,  1.7104,  0.4402,  0.7413],
        [-1.3820,  0.2723,  1.4675,  0.0988, -0.1917],
        [ 0.6581,  0.0657, -0.3591, -1.6286, -1.2775]], requires_grad=True)


In [11]:
# Xavier
# 均匀分布
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

# 正态分布
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.7123,  0.1588,  0.3853, -0.0176,  0.1740],
        [-0.4455, -0.1477, -0.2382,  0.7395,  0.6765],
        [ 0.0031,  0.2133,  0.6808, -0.7883, -0.1877]], requires_grad=True)
Parameter containing:
tensor([[-0.0719, -0.2089, -0.7165,  0.5809,  0.0598],
        [-0.3100, -0.0298, -0.1320, -0.5974, -0.4986],
        [-0.0560, -0.1526, -0.3586,  0.0845,  0.6307]], requires_grad=True)


In [13]:
# He
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

nn.init.normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.2993, -0.4847, -0.5254,  0.3112, -0.6024],
        [-0.4211, -1.0412,  0.4355,  0.1242, -0.7130],
        [-0.1621, -0.0767, -0.3998, -0.4443,  0.8190]], requires_grad=True)
Parameter containing:
tensor([[ 0.0890,  0.3502, -1.4198,  0.5718, -0.6688],
        [ 0.1585, -0.6457, -1.2360,  0.1484,  0.2018],
        [-1.2685,  0.5308, -0.1346, -0.3027,  0.2754]], requires_grad=True)
