In [8]:
import torch
import torch.nn as nn

In [9]:
x = torch.randn(3, 2)
print(x)

tensor([[-1.0283,  0.4520],
        [-1.5369,  0.7117],
        [-0.2346,  2.4683]])


In [10]:
t = torch.tensor([[0, 1], [1, 0], [0, 1]], dtype=torch.float)
print(t)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [11]:
y = torch.sigmoid(x)
print(y)

tensor([[0.2634, 0.6111],
        [0.1770, 0.6708],
        [0.4416, 0.9219]])


In [13]:
loss = nn.BCELoss()
print(loss(y, t))

tensor(0.7175)
