In [1]:
import torch
import torch.nn as nn

In [2]:
# 1. 真实值为类别标签(0-7)
x = torch.randn(6, 8)
print(x)

tensor([[-0.0589,  0.0875,  1.5303,  0.5240, -0.2288,  1.7803, -0.2908,  0.4739],
        [-0.1942,  0.8621,  0.6057,  0.1346,  0.4033, -0.4459, -0.9988,  1.1159],
        [ 0.2586, -0.4978, -0.2860, -0.8204,  0.0786, -0.9820,  0.5925,  0.1509],
        [-0.2484, -0.1120,  0.0353,  0.0563,  0.5771, -0.5609,  1.0766,  0.3414],
        [ 0.5225, -0.3198,  1.0078, -0.8099, -0.9242,  1.0833, -0.1011, -2.9058],
        [ 0.1266,  1.5739, -1.9500,  1.0299, -1.0574,  1.2391,  1.5837, -2.2372]])


In [3]:
t = torch.tensor([1, 0, 3, 2, 5, 7])
print(t)

tensor([1, 0, 3, 2, 5, 7])


In [4]:
loss = nn.CrossEntropyLoss()
print(loss(x, t))

tensor(2.8161)


In [5]:
# 2. 真实值为分类概率或独热码
t = torch.randn(6, 8).softmax(dim=1)
print(t)

tensor([[0.2959, 0.0096, 0.0838, 0.1925, 0.2009, 0.1200, 0.0248, 0.0726],
        [0.4885, 0.1297, 0.1342, 0.0257, 0.0453, 0.0134, 0.0888, 0.0744],
        [0.0105, 0.0471, 0.2956, 0.0731, 0.0397, 0.0424, 0.0978, 0.3936],
        [0.1286, 0.0259, 0.0567, 0.0080, 0.5129, 0.0896, 0.0232, 0.1550],
        [0.3122, 0.0379, 0.1974, 0.0351, 0.3225, 0.0341, 0.0557, 0.0052],
        [0.0219, 0.0363, 0.0624, 0.3443, 0.0268, 0.0107, 0.4283, 0.0692]])


In [6]:
print(loss(x, t))

tensor(2.2149)
